FROM public.ecr.aws/lambda/python:3.11

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/*.py ${LAMBDA_TASK_ROOT}/
COPY src/utils/ ${LAMBDA_TASK_ROOT}/utils/

CMD ["daily_sync.handler"]
